apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: serverless
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  channel: "4.5"
  name: serverless-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
